### ISSUE TITLE
Docker-compose部署

### ISSUE THREAD

**Issue by tangxs0808** [topiam/eiam-website#1]
## TOPIAM Docker-Compose部署 1.1.0最新版本 对接Alist保姆教程

>简介
>
>业界首个基于 SpringBoot3 开源IDaas/IAM平台，用于管理企业内员工账号、权限、身份认证、应用访问，帮助整合部署在本地或云端的内部办公系统、业务系统及三方 SaaS 系统的所有身份，实现一个账号打通所有应用的服务。支持OAuth2.x、OIDC、SAML2.0、JWT、CAS等SSO标准协议。

**本人近期一直都在找开源的OIDC项目，我也用过authing，但是只能免费创建一个应用。有国外的Casdoor 等一些轻量的开源项目，Casdoor不太符合国人的使用，碰巧遇到了TopIAM eiam项目，界面简洁，操作简单。**

>  _这是一篇本人实践中的摸索经验之谈，从搭建到应用。_

### Docker-compose部署

**先准备好conf文件**

目录式样 //当然你们也可以用一个文件

├── topiam
|   └── docker-compose.yaml
|       ├── conf
|       │   └── portal

|       │       │ ├──  topiam.properties

|       │   └── console

|       │       │ ├──  topiam.properties

> 这里1.1.0 版本已经去了两项依赖，所以配置文件会少一点内容

```
#datasource
spring.datasource.url=jdbc:mysql://数据库地址:3306/topiam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
spring.datasource.username=root //账号
spring.datasource.password=mysql //密码

#redis
spring.data.redis.host=172.18.0.1 //地址
spring.data.redis.port=6379
spring.data.redis.password=redis //密码

#springdoc
springdoc.swagger-ui.enabled=true

# server config
topiam.server.console-public-base-url=http://10.1.5.8:1898
topiam.server.portal-public-base-url=https://oidc.topiam.com //你的外网用户端域名
topiam.server.openapi-public-base-url=http://127.0.0.1:1988
topiam.server.synchronizer-public-base-url=http://127.0.0.1:1988

server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
```

```
version: '3.9'
services:
  eiam-portal-ce:
    container_name: eiam-portal-ce
    image: registry.cn-beijing.aliyuncs.com/ylwind/eiam-portal:1.1.0
    restart: always
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - '1989:1989'
    volumes:
      - '/topiam/conf/portal:/opt/topiam/conf'
    networks:
      - "iam"
    mem_limit: 4g

  eiam-console-ce:
    container_name: eiam-console-ce
    image: registry.cn-beijing.aliyuncs.com/ylwind/eiam-console:1.1.0
    restart: always
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - '1898:1898'
    volumes:
      - '/topiam/conf/console:/opt/topiam/conf'
    networks:
      - "iam"
    mem_limit: 4g
networks:
  iam:
    driver: bridge

```

**默认密码：admin/topiam.cn**

### Alist 对接 IAMTOP

**首先在我们的console控制台创建OIDC应用，获取客户端ID以及客户端密钥和Issuer**

**然后需要给予用户组权限**

 **根据下图填写配置即可完美对接，此处用户名键需要一一对应，否则获取不到用户名**

注意⚠️：需要关闭SSO兼容模式，oidc用户名键为：preferred_username

console控制台中 登录 Redirect URI 为：

```
https://alist.topiam.com/api/auth/sso_callback?method=get_sso_id
https://alist.topiam.com/api/auth/sso_callback?method=sso_get_token
```

![image-20240724160523233](https://raw.githubusercontent.com/tangxs0808/docker-mirror/main/image-20240724160523233.png)
